name = "PasajesChile Noticias"
license = "MIT"
licenselink = "//ggithub.com/gestsol/pasajes-chile-noticias/blob/master/LICENSE.md"
description = "Lovely wordpress theme, now coming to Hugo. "
homepage = "//github.com/gestsol/pasajes-chile-noticias"
tags = ["syntax highlighting", "rss", "widgets", "google analytics", "responsive", "carousel", "slider"]
features = ["syntax highlighting", "rss", "widgets", "google analytics", "carousel", "responsive", "slider"]
min_version = 0.15

[author]
  name = "Gestsol"
  homepage = "http://gestsol.cl/"

# If porting an existing theme
[original]
  name = "Pasajes Chile"
  homepage = "https://www.pasajeschile.cl/"
  repo = ""
