---
pages:
- post/cuarto-post.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
- name: author
  label: Author
  type: text
  hidden: false
  default: Pasajes Chile
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 2017-02-15 10:32:59 +0000
- name: banner
  label: Banner
  type: text
  hidden: false
  default: img/indiagate1.jpg
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - Asia
  - India
  - Pune
  - TheTravelBug
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ganesh chaturthi in pune
  - pune festivals
  - pune travel
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
