---
pages:
- post/quinto-post.md
- post/cuarto-post.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
- name: author
  label: Author
  type: text
  hidden: false
  default: Pasajes Chile
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 2017-02-15 10:32:59 +0000
  config:
    date_format: DD/MM/YYYY
    time_format: HH:mm A
- type: file
  label: Banner
  name: banner
  default: "/banners/placeholder.png"
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
