---
pages:
- post/full-width.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: 
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default:
  - Asia
  - India
  - Pune
  - TheTravelBug
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default:
  - ganesh chaturthi in pune
  - pune festivals
  - pune travel
- name: draft
  label: Borrador?
  type: boolean
  hidden: false
  default: ''
  description: Por defecto es NO
