---
pages:
- post/lanzamiento-de-pasajes-chile.md
- post/loren-ipsun.md
hide_body: false
fields:
- name: title
  label: Titulo
  type: text
  hidden: false
  default: ''
  description: Cual es el título de la publicación?
  config:
    required: true
- name: author
  label: Autor
  type: text
  hidden: false
  default: Pasajes Chile
  description: Quién publica?
  config:
    required: true
- name: date
  label: Fecha
  type: datetime
  hidden: false
  default: 2017-02-15 10:32:59 +0000
  config:
    date_format: DD/MM/YYYY
    time_format: HH:mm A
  description: Fecha de la publicación
- type: file
  label: Imagen destacada
  name: banner
  default: "/banners/placeholder.png"
  description: "Ésta imagen se mostrará en la página de Inicio, tanto en la cabecera
    del artículo como en el carrusel de los 6 últimos artículos publicados"
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
